version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: batch-demo
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      TZ: Asia/Seoul